"""initial schema

Revision ID: b8e9822a6a2b
Revises:
Create Date: 2026-03-02 11:29:56.418725

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b8e9822a6a2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fiis",
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("companyid", sa.String(length=80), nullable=True),
        sa.Column("companyname", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("sectorid", sa.Integer(), nullable=True),
        sa.Column("sectorname", sa.String(length=255), nullable=True),
        sa.Column("subsectorid", sa.Integer(), nullable=True),
        sa.Column("subsectorname", sa.String(length=255), nullable=True),
        sa.Column("segment", sa.String(length=255), nullable=True),
        sa.Column("segmentid", sa.Integer(), nullable=True),
        sa.Column("gestao", sa.Integer(), nullable=True),
        sa.Column("gestao_f", sa.String(length=255), nullable=True),
        sa.Column("dy", sa.Float(), nullable=True),
        sa.Column("p_vp", sa.Float(), nullable=True),
        sa.Column("valorpatrimonialcota", sa.Float(), nullable=True),
        sa.Column("liquidezmediadiaria", sa.Float(), nullable=True),
        sa.Column("percentualcaixa", sa.Float(), nullable=True),
        sa.Column("dividend_cagr", sa.Float(), nullable=True),
        sa.Column("cota_cagr", sa.Float(), nullable=True),
        sa.Column("numerocotistas", sa.Float(), nullable=True),
        sa.Column("numerocotas", sa.Float(), nullable=True),
        sa.Column("patrimonio", sa.Float(), nullable=True),
        sa.Column("lastdividend", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "stocks",
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("companyid", sa.String(length=80), nullable=True),
        sa.Column("companyname", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("p_l", sa.Float(), nullable=True),
        sa.Column("dy", sa.Float(), nullable=True),
        sa.Column("p_vp", sa.Float(), nullable=True),
        sa.Column("p_ebit", sa.Float(), nullable=True),
        sa.Column("p_ativo", sa.Float(), nullable=True),
        sa.Column("ev_ebit", sa.Float(), nullable=True),
        sa.Column("margembruta", sa.Float(), nullable=True),
        sa.Column("margemebit", sa.Float(), nullable=True),
        sa.Column("margemliquida", sa.Float(), nullable=True),
        sa.Column("p_sr", sa.Float(), nullable=True),
        sa.Column("p_capitalgiro", sa.Float(), nullable=True),
        sa.Column("p_ativocirculante", sa.Float(), nullable=True),
        sa.Column("giroativos", sa.Float(), nullable=True),
        sa.Column("roe", sa.Float(), nullable=True),
        sa.Column("roa", sa.Float(), nullable=True),
        sa.Column("roic", sa.Float(), nullable=True),
        sa.Column("dividaliquidapatrimonioliquido", sa.Float(), nullable=True),
        sa.Column("dividaliquidaebit", sa.Float(), nullable=True),
        sa.Column("pl_ativo", sa.Float(), nullable=True),
        sa.Column("passivo_ativo", sa.Float(), nullable=True),
        sa.Column("liquidezcorrente", sa.Float(), nullable=True),
        sa.Column("peg_ratio", sa.Float(), nullable=True),
        sa.Column("receitas_cagr5", sa.Float(), nullable=True),
        sa.Column("vpa", sa.Float(), nullable=True),
        sa.Column("lpa", sa.Float(), nullable=True),
        sa.Column("valormercado", sa.Float(), nullable=True),
        sa.Column("segmentid", sa.Integer(), nullable=True),
        sa.Column("sectorid", sa.Integer(), nullable=True),
        sa.Column("subsectorid", sa.Integer(), nullable=True),
        sa.Column("subsectorname", sa.String(length=255), nullable=True),
        sa.Column("segmentname", sa.String(length=255), nullable=True),
        sa.Column("sectorname", sa.String(length=255), nullable=True),
        sa.Column("graham_formula", sa.Float(), nullable=True),
        sa.Column("discount_to_graham", sa.Float(), nullable=True),
        sa.Column("roic_rank", sa.Integer(), nullable=True),
        sa.Column("ey_rank", sa.Integer(), nullable=True),
        sa.Column("magic_formula_rank", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("profile", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("stock_ticker", sa.String(length=10), nullable=True),
        sa.Column("ceiling_price", sa.Float(), nullable=True),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_ticker"],
            ["stocks.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "favorites_fii",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("fii_ticker", sa.String(length=10), nullable=True),
        sa.Column("ceiling_price", sa.Float(), nullable=True),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fii_ticker"],
            ["fiis.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_layouts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("layout", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_layouts")
    op.drop_table("favorites_fii")
    op.drop_table("favorites")
    op.drop_table("users")
    op.drop_table("stocks")
    op.drop_table("fiis")
    # ### end Alembic commands ###
